---
- name: provision new EC2 server
  hosts: localhost
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: provision t2.micro EC2 instance
    ec2:

      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: ami-e3bb7399
      instance_type: t2.micro
      count: 1
      vpc_subnet_id: subnet-112b2c3d
      assign_public_ip: yes

    register: ec2_details


  - name: add new t2.micro EC2 instance to Windows group
    add_host:
      name: "{{ item.public_ip }}"
      groups: windows
    with_items: "{{ ec2_details.instances }}"


- name: install features on new EC2 server
  hosts: windows
  gather_facts: no
  tasks:
  - name: wait for connection to be online
    wait_for_connection:

#  - name: install IIS Web-Server with sub features and management tools
#    win_feature:
#      name: Web-Server
#      state: present
#      include_sub_features: yes
#      include_management_features: yes
#    register: feature_install


#  - name: reboot if feature install requires it
#    win_reboot:
#    when: feature_install.reboot_required
