--- # EC2_AMI template.
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Copy AMI from one region to another
    ec2_ami_copy:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      source_region: "{{ aws_region }}"
      region: us-east-2
      source_image_id: ami-47f3793d
      wait: no
      name: useast2ami1
      tags:
        Name: East2AMI1
        Service: East2AMIService1
    register: instance
