--- # EC2_AMI Ansible for AWS, AMI template.
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Provisioning of an AMI for Ansible server
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key}}"
      region: "{{ aws_region }}"
      instance_id: i-0f1*******
      wait: no
      name: ansible
      tags:
        Name: AnsibleServer
        Service: AnsibleService
    register: instance
