--- # EC2 MODULE - PROVISIONING EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Provision of a set of Windows instances
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: ami-e3bb7399
      instance_type: t2.micro
      count: 1
      vpc_subnet_id: subnet-112b2c3d
      assign_public_ip: yes
      count_tag:
            Name: CountTagDemo
      instance_tags:
        Name: WinDemo      
    register: ec2

  - name: Print the results
    debug: var=item
    with_items: ec2.instances 

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=windows
    with_items: "{{ ec2.instances }}"

  - name: Wait for the instances to boot
    wait_for: state=started
    with_items: ec2.instances

- hosts: windows
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  
  tasks:
  - name: Install IIS
    win_feature:
      name: "Web-Server"
      state: present
      restart: true
      include_sub_features: yes
      include_management_tools: yes

